### ISSUE TITLE
Some training strange problem

### ISSUE THREAD

**Issue by DES4ssZ** [dylan-slack/manipulating-cfes#1]
Hello Dylan Slack,
sorry to disturb you. I have some problems running your code.
I have some strange results during running the attack of Wachter algorithm on the "Community and Crime" dataset.
My results are:
Protected tensor(6542.1655) tensor(2.2198e+09)
Not-Protected: tensor(774.7465) Var: tensor(27902444.)
Not-Protected + Delta: tensor(0.6296) Var: tensor(0.3044)
Delta tensor(5767.4189)
Cost Ratio tensor(1230.6257)

But I read your paper and found that your results are:
Protected 35.68
Non-Protected 35.31
Disparity 0.37
Non-Protected+δ 1.76 
Cost reduction 20.1

I will be truly grateful for your help!

Thank you for reading my problem, and please forgive my poor English.

**Comment by dylan-slack** [comment]
Closing because we followed up by e-mail and got this resolved
